CarMarket/src/java/entity/Brand.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

/**
 *
 * @author admin
 */
public class Brand {
    private int BrandId;
    private String BrandName;
    private String BrandImg;
    public Brand() {
    }

    public Brand(int BrandId, String BrandName, String BrandImg ) {
        this.BrandId = BrandId;
        this.BrandName = BrandName;
        this.BrandImg = BrandImg;
    }

    public Brand(String BrandName) {
        this.BrandName = BrandName;
    }

    public int getBrandId() {
        return BrandId;
    }

    public void setBrandId(int BrandId) {
        this.BrandId = BrandId;
    }

    public String getBrandName() {
        return BrandName;
    }

    public void setBrandName(String BrandName) {
        this.BrandName = BrandName;
    }

    public String getBrandImg() {
        return BrandImg;
    }

    public void setBrandImg(String BrandImg) {
        this.BrandImg = BrandImg;
    }

    public Brand(String BrandName, String BrandImg) {
        this.BrandName = BrandName;
        this.BrandImg = BrandImg;
    }
    
    
    
}

CarMarket/src/java/entity/CarImage.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

/**
 *
 * @author admin
 */
public class CarImage {
    private int ImageID;
    private int postId;
    private String postImg;

    public CarImage() {
    }

    public CarImage(int ImageID, int postId, String postImg) {
        this.ImageID = ImageID;
        this.postId = postId;
        this.postImg = postImg;
    }

    public CarImage(int postId, String postImg) {
        this.postId = postId;
        this.postImg = postImg;
    }

    public CarImage(String postImg) {
        this.postImg = postImg;
    }

    public int getImageID() {
        return ImageID;
    }

    public void setImageID(int ImageID) {
        this.ImageID = ImageID;
    }

    public int getPostId() {
        return postId;
    }

    public void setPostId(int postId) {
        this.postId = postId;
    }

    public String getPostImg() {
        return postImg;
    }

    public void setPostImg(String postImg) {
        this.postImg = postImg;
    }
    
    
}

CarMarket/src/java/entity/Feedback.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

import java.util.Date;

/**
 *
 * @author admin
 */
public class Feedback {
    private int FeedbackId;
    private String note;
    private String rank;
    private Date createDate;
    private int userId;

    public Feedback() {
    }

    public Feedback(int FeedbackId, String note, String rank, Date createDate, int userId) {
        this.FeedbackId = FeedbackId;
        this.note = note;
        this.rank = rank;
        this.createDate = createDate;
        this.userId = userId;
    }

    public Feedback(String note, String rank, Date createDate) {
        this.note = note;
        this.rank = rank;
        this.createDate = createDate;
    }

    public Feedback(String note, String rank, Date createDate, int userId) {
        this.note = note;
        this.rank = rank;
        this.createDate = createDate;
        this.userId = userId;
    }
    
    

    public int getFeedbackId() {
        return FeedbackId;
    }

    public void setFeedbackId(int FeedbackId) {
        this.FeedbackId = FeedbackId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getRank() {
        return rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    
}

CarMarket/src/java/entity/Model.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

/**
 *
 * @author admin
 */
public class Model {
    private int ModelId;
    private String ModelName;
    private String ModelImg;

    public Model() {
    }

    public Model(int ModelId, String ModelName, String ModelImg) {
        this.ModelId = ModelId;
        this.ModelName = ModelName;
        this.ModelImg = ModelImg;
    }

    public Model(String ModelName) {
        this.ModelName = ModelName;
    }

    public int getModelId() {
        return ModelId;
    }

    public void setModelId(int ModelId) {
        this.ModelId = ModelId;
    }

    public String getModelName() {
        return ModelName;
    }

    public void setModelName(String ModelName) {
        this.ModelName = ModelName;
    }

    public String getModelImg() {
        return ModelImg;
    }

    public void setModelImg(String ModelImg) {
        this.ModelImg = ModelImg;
    }
    
    
    
    
}

CarMarket/src/java/entity/engine.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

/**
 *
 * @author admin
 */
public class engine {
    private int EngineID;
    private String EngineName;

    public engine() {
    }

    public engine(int EngineID, String EngineName) {
        this.EngineID = EngineID;
        this.EngineName = EngineName;
    }

    public engine(String EngineName) {
        this.EngineName = EngineName;
    }

    public int getEngineID() {
        return EngineID;
    }

    public void setEngineID(int EngineID) {
        this.EngineID = EngineID;
    }

    public String getEngineName() {
        return EngineName;
    }

    public void setEngineName(String EngineName) {
        this.EngineName = EngineName;
    }
    
    
}

CarMarket/src/java/entity/exteriorColor.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

/**
 *
 * @author admin
 */
public class exteriorColor {
    private int ExteriorColorID;
    private String ExteriorColorName;

    public exteriorColor() {
    }

    public exteriorColor(int ExteriorColorID, String ExteriorColorName) {
        this.ExteriorColorID = ExteriorColorID;
        this.ExteriorColorName = ExteriorColorName;
    }

    public exteriorColor(String ExteriorColorName) {
        this.ExteriorColorName = ExteriorColorName;
    }

    public int getExteriorColorID() {
        return ExteriorColorID;
    }

    public void setExteriorColorID(int ExteriorColorID) {
        this.ExteriorColorID = ExteriorColorID;
    }

    public String getExteriorColorName() {
        return ExteriorColorName;
    }

    public void setExteriorColorName(String ExteriorColorName) {
        this.ExteriorColorName = ExteriorColorName;
    }
    
    
}

CarMarket/src/java/entity/gearbox.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package entity;

/**
 *
 * @author admin
 */
public class gearbox {
    private int GearboxID;
    private String GearboxName;

    public gearbox() {
    }

    public gearbox(int GearboxID, String GearboxName) {
        this.GearboxID = GearboxID;
        this.GearboxName = GearboxName;
    }

    public gearbox(String GearboxName) {
        this.GearboxName = GearboxName;
    }

    public int getGearboxID() {
        return GearboxID;
    }

    public void setGearboxID(int GearboxID) {
        this.GearboxID = GearboxID;
    }

    public String getGearboxName() {
        return GearboxName;
    }

    public void setGearboxName(String GearboxName) {
        this.GearboxName = GearboxName;
    }
    
    
}

CarMarket/src/java/model/DBConnect.java
package model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DBConnect {
    Connection conn = null;

    public DBConnect(String URL, String userName, String pass) {
        try {
            // Driver
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            // Connect
            conn = DriverManager.getConnection(URL, userName, pass);
            System.out.println("Connection successful");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, "Driver not found", ex);
        } catch (SQLException ex) {
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, "Failed to connect to the database", ex);
        }
    }

    public ResultSet getData(String sql) {
        ResultSet rs = null;
        Statement state;
        try {
            state = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = state.executeQuery(sql);
        } catch (SQLException e) {
            Logger.getLogger(DBConnect.class.getName()).log(Level.SEVERE, "Failed to execute query", e);
        }
        return rs;
    }

    public DBConnect() {
        this("jdbc:sqlserver://localhost:1433;databaseName=CarMarket1_0", "sa", "123456");
    }

    public static void main(String[] args) {
        new DBConnect();
    }
}

CarMarket/src/java/controller/ForgetPasswordServlet.java
package controller;

import entity.Client;
import entity.Provider;
import entity.email;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import model.DAOClient;
import model.DAOProvider;
import java.util.logging.Level;
import java.util.logging.Logger;

@WebServlet(name = "ForgetPasswordServlet", urlPatterns = {"/forgetpassword"})
public class ForgetPasswordServlet extends HttpServlet {

    private static final Logger LOGGER = Logger.getLogger(ForgetPasswordServlet.class.getName());

    private static String hideEmail(String email) {
        String[] parts = email.split("@");
        String localPart = parts[0];
        String domainPart = parts[1];
        StringBuilder hiddenLocalPart = new StringBuilder(localPart.substring(0, 1));
        for (int i = 1; i < localPart.length(); i++) {
            hiddenLocalPart.append("*");
        }
        return hiddenLocalPart.toString() + "@" + domainPart;
    }

    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        DAOClient cliDao = new DAOClient();
        DAOProvider proDao = new DAOProvider();
        HttpSession session = request.getSession();
        email mail = new email();

        String lostPass = request.getParameter("lostPass");
        if (lostPass == null || lostPass.isEmpty()) {
            lostPass = "getTheMail";
        }

        try (PrintWriter out = response.getWriter()) {
            if ("getTheMail".equals(lostPass)) {
                String getEmail = request.getParameter("getEmail");
                if (getEmail == null || getEmail.isEmpty()) {
                    request.setAttribute("wrongEmail", "Email cannot be empty.");
                    request.getRequestDispatcher("JSP/forgetPassword.jsp").forward(request, response);
                    return;
                }

                Client client = cliDao.getClientByEmail(getEmail);
                Provider provider = proDao.getProviderByEmail(getEmail);

                if (client != null) {
                    session.setAttribute("acc", client);
                    String otp = mail.sendVerificaionOTPUsingEmail(client.getEmail());
                    session.setAttribute("theOTP", otp);
                    session.setMaxInactiveInterval(2 * 60); // 2 minutes
                    session.setAttribute("userEmail", client.getEmail()); // Save full email
                    session.setAttribute("userMail", hideEmail(client.getEmail()));
                    request.getRequestDispatcher("JSP/VerifyOTP.jsp").forward(request, response);
                } else if (provider != null) {
                    session.setAttribute("acc", provider);
                    String otp = mail.sendVerificaionOTPUsingEmail(provider.getEmail());
                    session.setAttribute("theOTP", otp);
                    session.setMaxInactiveInterval(2 * 60); // 2 minutes
                    session.setAttribute("userEmail", provider.getEmail()); // Save full email
                    session.setAttribute("userMail", hideEmail(provider.getEmail()));
                    request.getRequestDispatcher("JSP/VerifyOTP.jsp").forward(request, response);
                } else {
                    request.setAttribute("wrongEmail", "The Email you entered does not match with any registered email account. Try again.");
                    request.getRequestDispatcher("JSP/forgetPassword.jsp").forward(request, response);
                }
            } else if ("verifyOTP".equals(lostPass)) {
                String userOTP = request.getParameter("op1") + request.getParameter("op2")
                        + request.getParameter("op3") + request.getParameter("op4")
                        + request.getParameter("op5") + request.getParameter("op6");
                String theOTP = (String) session.getAttribute("theOTP");

                if (userOTP.equals(theOTP)) {
                    String userEmail = (String) session.getAttribute("userEmail");
                    Client client = cliDao.getClientByEmail(userEmail);
                    Provider provider = proDao.getProviderByEmail(userEmail);

                    if (client != null) {
                        session.setAttribute("currentAcc", client);
                        request.getRequestDispatcher("/JSP/home.jsp").forward(request, response);
                    } else if (provider != null) {
                        session.setAttribute("currentAcc", provider);
                        request.getRequestDispatcher("/JSP/home.jsp").forward(request, response);
                    }
                } else {
                    request.setAttribute("wrongOTP", "The OTP code is incorrect, Try again.");
                    request.getRequestDispatcher("JSP/VerifyOTP.jsp").forward(request, response);
                }
            } else if ("resendOTP".equals(lostPass)) {
                String userEmail = (String) session.getAttribute("userEmail");
                if (userEmail != null) {
                    Client client = cliDao.getClientByEmail(userEmail);
                    Provider provider = proDao.getProviderByEmail(userEmail);

                    if (client != null) {
                        String otp = mail.sendVerificaionOTPUsingEmail(client.getEmail());
                        session.setAttribute("theOTP", otp);
                        session.setMaxInactiveInterval(2 * 60); // 2 minutes
                    } else if (provider != null) {
                        String otp = mail.sendVerificaionOTPUsingEmail(provider.getEmail());
                        session.setAttribute("theOTP", otp);
                        session.setMaxInactiveInterval(2 * 60); // 2 minutes
                    }
                    request.getRequestDispatcher("JSP/VerifyOTP.jsp").forward(request, response);
                } else {
                    request.setAttribute("wrongEmail", "Email session expired or not found. Try again.");
                    request.getRequestDispatcher("JSP/forgetPassword.jsp").forward(request, response);
                }
            } else {
                request.getRequestDispatcher("JSP/forgetPassword.jsp").forward(request, response);
            }
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Error processing request", e);
            request.setAttribute("errorMessage", "An unexpected error occurred. Please try again.");
            request.getRequestDispatcher("JSP/forgetPassword.jsp").forward(request, response);
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    @Override
    public String getServletInfo() {
        return "Servlet for handling forgot password functionality";
    }
}

CarMarket/web/JSP/detailPostForClient.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>eCommerce Product Detail</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
        <style>
            body {
                font-family: 'open sans';
                overflow-x: hidden;
            }
            img {
                max-width: 100%;
            }
            .preview {
                display: flex;
                flex-direction: column;
            }
            @media screen and (max-width: 996px) {
                .preview {
                    margin-bottom: 20px;
                }
            }
            .preview-pic {
                flex-grow: 1;
            }
            .preview-thumbnail.nav-tabs {
                border: none;
                margin-top: 15px;
            }
            .preview-thumbnail.nav-tabs li {
                width: 18%;
                margin-right: 2.5%;
            }
            .preview-thumbnail.nav-tabs li img {
                max-width: 100%;
                display: block;
            }
            .preview-thumbnail.nav-tabs li a {
                padding: 0;
                margin: 0;
            }
            .preview-thumbnail.nav-tabs li:last-of-type {
                margin-right: 0;
            }
            .tab-content {
                overflow: hidden;
            }
            .tab-content img {
                width: 100%;
                animation-name: opacity;
                animation-duration: .3s;
            }
            .card {
                margin-top: 50px;
                background: #eee;
                padding: 3em;
                line-height: 1.5em;
            }
            @media screen and (min-width: 997px) {
                .wrapper {
                    display: flex;
                }
            }
            .details {
                display: flex;
                flex-direction: column;
            }
            .colors {
                flex-grow: 1;
            }
            .product-title, .price, .sizes, .colors {
                text-transform: UPPERCASE;
                font-weight: bold;
            }
            .checked, .price span {
                color: #ff9f1a;
            }
            .product-title, .rating, .product-description, .price, .vote, .sizes {
                margin-bottom: 15px;
            }
            .product-title {
                margin-top: 0;
            }
            .size {
                margin-right: 10px;
            }
            .size:first-of-type {
                margin-left: 40px;
            }
            .color {
                display: inline-block;
                vertical-align: middle;
                margin-right: 10px;
                height: 2em;
                width: 2em;
                border-radius: 2px;
            }
            .color:first-of-type {
                margin-left: 20px;
            }
            .add-to-cart, .like {
                background: #ff9f1a;
                padding: 1.2em 1.5em;
                border: none;
                text-transform: UPPERCASE;
                font-weight: bold;
                color: #fff;
                transition: background .3s ease;
            }
            .add-to-cart:hover, .like:hover {
                background: #b36800;
                color: #fff;
            }
            .not-available {
                text-align: center;
                line-height: 2em;
            }
            .not-available:before {
                font-family: fontawesome;
                content: "\f00d";
                color: #fff;
            }
            .orange {
                background: #ff9f1a;
            }
            .green {
                background: #85ad00;
            }
            .blue {
                background: #0076ad;
            }
            .tooltip-inner {
                padding: 1.3em;
            }
            @keyframes opacity {
                0% {
                    opacity: 0;
                    transform: scale(3);
                }
                100% {
                    opacity: 1;
                    transform: scale(1);
                }
            }
            .navbar-nav .dropdown-menu {
                min-width: 200px;
            }
            .dropdown-item {
                font-size: 14px;
                padding: 5px 10px;
            }
            .notification {
                background-color: red;
                color: white;
                border-radius: 50%;
                padding: 2px 6px;
                font-size: 12px;
                position: relative;
                top: -10px;
                right: 10px;
            }
        </style>
    </head>
    <body>
        <div class="collapse navbar-collapse menu-ui-design" id="navbar-menu">
            <ul class="nav navbar-nav navbar-right" data-in="fadeInDown" data-out="fadeOutUp">
                <c:choose>
                    <c:when test="${sessionScope.userType == 'client'}">
                        <li class="scroll active"><a href="/carmarket/login">Home</a></li>
                        </c:when>
                        <c:when test="${sessionScope.currentAcc != null}">
                        <li class="scroll active"><a href="/carmarket/home">Home</a></li>
                    </c:when>
                </c:choose>
                
                    <c:choose>
                        <c:when test="${sessionScope.currentAcc == null}">
                        <li><a href="JSP/Login.jsp">Login</a></li>
                        </c:when>
                        <c:when test="${sessionScope.userType == 'client'}">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Service <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="profile">Manage Account</a></li>
                                <li><a class="dropdown-item" href="managePostClient">Manage Post</a></li>
                                <li><a class="dropdown-item" href="manageCar">Manage Car</a></li>
                                <li><a class="dropdown-item" href="createPost">Create Post</a></li>
                            </ul>
                        </li>
                        <li><a href="logout">Logout</a></li>
                        </c:when>
                        <c:when test="${sessionScope.currentAcc != null}">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage Service <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="managecustomerprofile">Manage Customer Account</a></li>
                                <li>
                                    <a class="dropdown-item" href="managePost">Manage Post
                                        <c:if test="${applicationScope.newPostCount > 0}">
                                            <span class="notification">${applicationScope.newPostCount}</span>
                                        </c:if>
                                    </a>
                                </li>
                                <li><a class="dropdown-item" href="manageCar">Manage Car</a></li>
                            </ul>
                        </li>
                        <li><a href="logout">Logout</a></li>
                        </c:when>
                    </c:choose>
            </ul>
        </div>

        <div class="container">
            <div class="card">
                <div class="container-fliud">
                    <div class="wrapper row">
                        <div class="preview col-md-6">
                            <div class="preview-pic tab-content">
                                <div class="tab-pane active" id="pic-1"><img src="${image[0].postImg}" /></div>
                            </div>
                            <ul class="preview-thumbnail nav nav-tabs">
                                <c:forEach var="image" items="${image}">
                                    <li><a data-target="#pic-1" data-toggle="tab"><img src="${image.postImg}" /></a></li>
                                        </c:forEach>
                            </ul>
                        </div>
                        <div class="details col-md-6">
                            <h3 class="product-title">${post.carName}</h3>
                            <div class="rating">
                                <div class="stars">
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                </div>
                                <span class="review-no" >This post was posted by<a href="viewProfileByClient?clientId=${client.clientId}" >${client.firstName} ${client.lastName}</a></span>
                            </div>
                            <p class="product-description">${post.descriptions}</p>
                            <h4 class="price">price: <span><fmt:formatNumber value="${post.priceCar}" pattern="#,##0"/> VND</span></h4>
                            <h5 class="colors">Brand: <span class="size" data-toggle="tooltip" title="small">${br.brandName}</span></h5>
                            <h5 class="colors">Model: <span class="size" data-toggle="tooltip" title="small">${md.modelName}</span></h5>
                            <h5 class="colors">Number Of Seats: <span class="size" data-toggle="tooltip" title="small">${seats.numberOfSeatsName}</span></h5>
                            <h5 class="colors">Number Of Doors: <span class="size" data-toggle="tooltip" title="small">${doors.numberOfDoorsName}</span></h5>
                            <h5 class="colors">Interior Color: <span class="size" data-toggle="tooltip" title="small">${inColor.interiorColorName}</span></h5>
                            <h5 class="colors">Exterior Color: <span class="size" data-toggle="tooltip" title="small">${exColor.exteriorColorName}</span></h5>
                            <h5 class="colors">Gearbox: <span class="size" data-toggle="tooltip" title="small">${gb.gearboxName}</span></h5>
                            <h5 class="colors">Engine: <span class="size" data-toggle="tooltip" title="small">${eg.engineName}</span></h5>
                            <div class="action">
                                <button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

CarMarket/web/JSP/success.jsp
<%-- 
    Document   : success
    Created on : Jun 18, 2024, 2:17:54 PM
    Author     : admin
--%>

<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Success Page</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #87CEEB; /* Màu xanh nước biển */
                margin: 0;
                padding: 0;
            }
            .container {
                width: 50%;
                margin: 100px auto;
                padding: 20px;
                background-color: #fff;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                border-radius: 10px;
                text-align: center;
            }
            h1 {
                color: #4CAF50;
            }
            p {
                font-size: 18px;
                color: #555;
            }
            .btn-home {
                display: inline-block;
                padding: 10px 20px;
                font-size: 16px;
                color: #fff;
                background-color: #4CAF50;
                border: none;
                border-radius: 5px;
                text-decoration: none;
                transition: background-color 0.3s;
                cursor: pointer;
            }
            .btn-home:hover {
                background-color: #45a049;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <form action="/carmarket/login" method="get">
                <h1>Your Action Done Successfully!</h1>
                <p>Your action have finish successfully. Please wait a moment while we process it.</p>
                <input type="submit" class="btn-home" value="Back to Homepage">
                <p>Thank you for your patience.</p>
            </form>
        </div>
    </body>
</html>